from sqlalchemy import VARCHAR, Integer, Float
from sqlalchemy.orm import Mapped, mapped_column
from database import Base

class PurchaseCostVariance(Base):
    __tablename__ = "T_PurchaseCostVariance"
    __table_args__ = {"extend_existing": True}

    年月: Mapped[int] = mapped_column("年月", Integer, primary_key=True)
    セグメント: Mapped[str] = mapped_column("セグメント", VARCHAR(30), primary_key=True)
    購入原価差額科目: Mapped[str] = mapped_column("購入原価差額科目", VARCHAR(50), primary_key=True)
    金額: Mapped[float] = mapped_column("金額", Float(53))

class CostCenterReports(Base):
    __tablename__ = "T_CostCenterReport"
    __table_args__ = {"extend_existing": True}

    column1: Mapped[str] = mapped_column("年月", VARCHAR(50), primary_key=True)
    column2: Mapped[str] = mapped_column("集計キー", VARCHAR(50))
    column3: Mapped[str] = mapped_column("集計キー名称", VARCHAR(50))
    column4: Mapped[str] = mapped_column("レコードタイプ", VARCHAR(50))
    column5: Mapped[str] = mapped_column("WBS 要素", VARCHAR(50))
    column6: Mapped[str] = mapped_column("製番", VARCHAR(50))
    column7: Mapped[str] = mapped_column("製番テキスト", VARCHAR(50))
    column8: Mapped[str] = mapped_column("得意先グループ", VARCHAR(50))
    column9: Mapped[str] = mapped_column("得意先コード", VARCHAR(50))
    column10: Mapped[str] = mapped_column("得意先名", VARCHAR(50))
    column11: Mapped[str] = mapped_column("販売伝票タイプ", VARCHAR(50))
    column12: Mapped[str] = mapped_column("受注伝票番号", VARCHAR(50), primary_key=True)
    column13: Mapped[str] = mapped_column("受注伝票明細", VARCHAR(50), primary_key=True)
    column14: Mapped[str] = mapped_column("明細カテゴリ", VARCHAR(50))
    column15: Mapped[str] = mapped_column("受注数量", VARCHAR(50))
    column16: Mapped[str] = mapped_column("受注金額（外貨）", VARCHAR(50))
    column17: Mapped[str] = mapped_column("通貨", VARCHAR(50))
    column18: Mapped[str] = mapped_column("受注金額", VARCHAR(50))
    column19: Mapped[str] = mapped_column("販売単位", VARCHAR(50))
    column20: Mapped[str] = mapped_column("販売地域", VARCHAR(50))
    column21: Mapped[str] = mapped_column("伝票カテゴリ", VARCHAR(50))
    column22: Mapped[str] = mapped_column("用途使用先", VARCHAR(50))
    column23: Mapped[str] = mapped_column("SINo.", VARCHAR(50))
    column24: Mapped[str] = mapped_column("管理番号(明細)", VARCHAR(50))
    column25: Mapped[str] = mapped_column("品目グループ", VARCHAR(50))
    column26: Mapped[str] = mapped_column("品目コード", VARCHAR(50))
    column27: Mapped[str] = mapped_column("プラント", VARCHAR(50))
    column28: Mapped[str] = mapped_column("保管場所", VARCHAR(50))
    column29: Mapped[str] = mapped_column("品目テキスト", VARCHAR(50))
    column30: Mapped[str] = mapped_column("品目階層", VARCHAR(50))
    column31: Mapped[str] = mapped_column("調達タイプ", VARCHAR(50))
    column32: Mapped[str] = mapped_column("特殊調達タイプ", VARCHAR(50))
    column33: Mapped[str] = mapped_column("実在庫移動日", VARCHAR(50))
    column34: Mapped[str] = mapped_column("請求日", VARCHAR(50))
    column35: Mapped[str] = mapped_column("指定納期", VARCHAR(50))
    column36: Mapped[str] = mapped_column("上位レベル明細", VARCHAR(50))
    column37: Mapped[str] = mapped_column("営業グループ", VARCHAR(50))
    column38: Mapped[str] = mapped_column("営業所", VARCHAR(50))
    column39: Mapped[str] = mapped_column("予算（売上高）", VARCHAR(50))
    column40: Mapped[str] = mapped_column("予算（原価１）", VARCHAR(50))
    column41: Mapped[str] = mapped_column("予算（原価２）", VARCHAR(50))
    column42: Mapped[str] = mapped_column("予算（原価３）", VARCHAR(50))
    column43: Mapped[str] = mapped_column("予算（原価４）", VARCHAR(50))
    column44: Mapped[str] = mapped_column("予算（原価５）", VARCHAR(50))
    column45: Mapped[str] = mapped_column("計画（直接費）", VARCHAR(50))
    column46: Mapped[str] = mapped_column("材料費（計画）", VARCHAR(50))
    column47: Mapped[str] = mapped_column("購入品費（計画）", VARCHAR(50))
    column48: Mapped[str] = mapped_column("外注費（計画）", VARCHAR(50))
    column49: Mapped[str] = mapped_column("計画（間接費）", VARCHAR(50))
    column50: Mapped[str] = mapped_column("加工（計画）", VARCHAR(50))
    column51: Mapped[str] = mapped_column("組立（計画）", VARCHAR(50))
    column52: Mapped[str] = mapped_column("摩擦材/鋳込（計画）", VARCHAR(50))
    column53: Mapped[str] = mapped_column("シートメタル/検査（計画）", VARCHAR(50))
    column54: Mapped[str] = mapped_column("研究開発/管理費（計画）", VARCHAR(50))
    column55: Mapped[str] = mapped_column("管理費/なし（計画）", VARCHAR(50))
    column56: Mapped[str] = mapped_column("実績累計（出荷数量）", VARCHAR(50))
    column57: Mapped[str] = mapped_column("実績累計（売上高）", VARCHAR(50))
    column58: Mapped[str] = mapped_column("実績累計（直接費）", VARCHAR(50))
    column59: Mapped[str] = mapped_column("材料費（実績累計）", VARCHAR(50))
    column60: Mapped[str] = mapped_column("購入品費（実績累計）", VARCHAR(50))
    column61: Mapped[str] = mapped_column("外注費（実績累計）", VARCHAR(50))
    column62: Mapped[str] = mapped_column("実績累計（間接費）", VARCHAR(50))
    column63: Mapped[str] = mapped_column("加工（実績累計）", VARCHAR(50))
    column64: Mapped[str] = mapped_column("組立（実績累計）", VARCHAR(50))
    column65: Mapped[str] = mapped_column("摩擦材/鋳込（実績累計）", VARCHAR(50))
    column66: Mapped[str] = mapped_column("シートメタル/検査（実績累計）", VARCHAR(50))
    column67: Mapped[str] = mapped_column("研究開発/管理費（実績累計）", VARCHAR(50))
    column68: Mapped[str] = mapped_column("管理費/なし（実績累計）", VARCHAR(50))
    column69: Mapped[str] = mapped_column("実績累計(直課費用：原価1)", VARCHAR(50))
    column70: Mapped[str] = mapped_column("実績累計(直課費用：原価2)", VARCHAR(50))
    column71: Mapped[str] = mapped_column("実績累計(直課費用：原価3)", VARCHAR(50))
    column72: Mapped[str] = mapped_column("実績累計(直課費用：原価4)", VARCHAR(50))
    column73: Mapped[str] = mapped_column("実績累計(直課費用：原価5)", VARCHAR(50))
    column74: Mapped[str] = mapped_column("実績累計(原価差額：直接費)", VARCHAR(50))
    column75: Mapped[str] = mapped_column("実績累計(原価差額：間接費)", VARCHAR(50))
    column76: Mapped[str] = mapped_column("実績累計(作業)", VARCHAR(50))
    column77: Mapped[str] = mapped_column("実績当月(出荷数量)", VARCHAR(50))
    column78: Mapped[str] = mapped_column("実績当月(売上高)", VARCHAR(50))
    column79: Mapped[str] = mapped_column("実績当月(直接費）", VARCHAR(50))
    column80: Mapped[str] = mapped_column("材料費（実績当月）", VARCHAR(50))
    column81: Mapped[str] = mapped_column("購入品費（実績当月）", VARCHAR(50))
    column82: Mapped[str] = mapped_column("外注費（実績当月）", VARCHAR(50))
    column83: Mapped[str] = mapped_column("実績当月(間接費）", VARCHAR(50))
    column84: Mapped[str] = mapped_column("加工（実績当月）", VARCHAR(50))
    column85: Mapped[str] = mapped_column("組立（実績当月）", VARCHAR(50))
    column86: Mapped[str] = mapped_column("摩擦材/鋳込（実績当月）", VARCHAR(50))
    column87: Mapped[str] = mapped_column("シートメタル/検査（実績当月）", VARCHAR(50))
    column88: Mapped[str] = mapped_column("研究開発/管理費（実績当月）", VARCHAR(50))
    column89: Mapped[str] = mapped_column("管理費/なし（実績当月）", VARCHAR(50))
    column90: Mapped[str] = mapped_column("実績当月(直課費用：原価1)", VARCHAR(50))
    column91: Mapped[str] = mapped_column("実績当月(直課費用：原価2)", VARCHAR(50))
    column92: Mapped[str] = mapped_column("実績当月(直課費用：原価3)", VARCHAR(50))
    column93: Mapped[str] = mapped_column("実績当月(直課費用：原価4)", VARCHAR(50))
    column94: Mapped[str] = mapped_column("実績当月(直課費用：原価5)", VARCHAR(50))
    column95: Mapped[str] = mapped_column("実績当月(原価差額：直接費)", VARCHAR(50))
    column96: Mapped[str] = mapped_column("実績当月(原価差額：間接費)", VARCHAR(50))
    column97: Mapped[str] = mapped_column("実績当月(作業）", VARCHAR(50))
    column98: Mapped[str] = mapped_column("カレント（直接費）", VARCHAR(50))
    column99: Mapped[str] = mapped_column("材料費（カレント）", VARCHAR(50))
    column100: Mapped[str] = mapped_column("購入品費（カレント）", VARCHAR(50))
    column101: Mapped[str] = mapped_column("外注費（カレント）", VARCHAR(50))
    column102: Mapped[str] = mapped_column("カレント（間接費）", VARCHAR(50))
    column103: Mapped[str] = mapped_column("加工（カレント）", VARCHAR(50))
    column104: Mapped[str] = mapped_column("組立（カレント）", VARCHAR(50))
    column105: Mapped[str] = mapped_column("摩擦材/鋳込（カレント）", VARCHAR(50))
    column106: Mapped[str] = mapped_column("シートメタル/検査（カレント）", VARCHAR(50))
    column107: Mapped[str] = mapped_column("研究開発/管理費（カレント）", VARCHAR(50))
    column108: Mapped[str] = mapped_column("管理費/なし（カレント）", VARCHAR(50))
    column109: Mapped[str] = mapped_column("原価", VARCHAR(50))

class ActualExpenses(Base):
    __tablename__ = "T_ExpenseActuals"
    __table_args__ = {"extend_existing": True}

    column1: Mapped[str] = mapped_column("年月", VARCHAR(50))
    column2: Mapped[str] = mapped_column("原価センタ", VARCHAR(50))
    column3: Mapped[str] = mapped_column("原価要素", VARCHAR(50))
    column4: Mapped[str] = mapped_column("原価要素名", VARCHAR(50))
    column5: Mapped[str] = mapped_column("参照伝票番号", VARCHAR(50))
    column6: Mapped[str] = mapped_column("名称", VARCHAR(50))
    column7: Mapped[str] = mapped_column("転記日付", VARCHAR(50))
    column8: Mapped[str] = mapped_column("金額", VARCHAR(50))
    column9: Mapped[str] = mapped_column("ObCur", VARCHAR(50))
    column10: Mapped[str] = mapped_column("現地通貨額", VARCHAR(50))
    column11: Mapped[str] = mapped_column("TCurr", VARCHAR(50))
    column12: Mapped[str] = mapped_column("会社コード", VARCHAR(50))
    column13: Mapped[str] = mapped_column("論理システム (元)", VARCHAR(50))
    id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True) 

class SalesReceivables(Base):
    __tablename__ = "T_SBU_SalesReceivables"
    __table_args__ = {"extend_existing": True}

    column1: Mapped[str] = mapped_column("BusA", VARCHAR(50))
    column2: Mapped[str] = mapped_column("事業領域名称", VARCHAR(50))
    column3: Mapped[str] = mapped_column("得意先", VARCHAR(50), primary_key=True)
    column4: Mapped[str] = mapped_column("得意先名称", VARCHAR(50))
    column5: Mapped[str] = mapped_column("勘定", VARCHAR(50), primary_key=True)
    column6: Mapped[str] = mapped_column("勘定名称", VARCHAR(50))
    column7: Mapped[str] = mapped_column("営業所コード", VARCHAR(50), primary_key=True)
    column9: Mapped[str] = mapped_column("通貨", VARCHAR(50))
    column10: Mapped[str] = mapped_column("年月", VARCHAR(50), primary_key=True)
    column11: Mapped[str] = mapped_column("前月繰越", VARCHAR(50))
    column12: Mapped[str] = mapped_column("当月増加", VARCHAR(50))
    column13: Mapped[str] = mapped_column("当月減少", VARCHAR(50))
    column14: Mapped[str] = mapped_column("当月残高", VARCHAR(50))

class Discounts(Base):
    __tablename__ = "T_DiscountList"
    __table_args__ = {"extend_existing": True}

    column1: Mapped[str] = mapped_column("年月", VARCHAR(50), primary_key=True)
    column2: Mapped[str] = mapped_column("販売伝票", VARCHAR(50), primary_key=True)
    column3: Mapped[str] = mapped_column("明細", VARCHAR(50), primary_key=True)
    column4: Mapped[str] = mapped_column("受注先", VARCHAR(50))
    column5: Mapped[str] = mapped_column("受注先名称", VARCHAR(50))
    column6: Mapped[str] = mapped_column("WBS要素", VARCHAR(50))
    column7: Mapped[str] = mapped_column("品階", VARCHAR(50))
    column8: Mapped[str] = mapped_column("品G", VARCHAR(50))
    column9: Mapped[str] = mapped_column("販地", VARCHAR(50))
    column10: Mapped[str] = mapped_column("品目コード", VARCHAR(50))
    column11: Mapped[str] = mapped_column("品目テキスト", VARCHAR(50))
    column12: Mapped[str] = mapped_column("数量", VARCHAR(50))
    column13: Mapped[str] = mapped_column("単位", VARCHAR(50))
    column14: Mapped[str] = mapped_column("売上高", VARCHAR(50))
    column15: Mapped[str] = mapped_column("売上原価", VARCHAR(50))

class StaffingSummary(Base): 
    __tablename__ = "T_PersonnelSummary"
    __table_args__ = {"extend_existing": True} 

    年月: Mapped[int] = mapped_column("年月", Integer, primary_key=True)
    セグメント: Mapped[str] = mapped_column("セグメント", VARCHAR(10), primary_key=True)
    分類: Mapped[str] = mapped_column("分類", VARCHAR(30), primary_key=True)
    人員: Mapped[float] = mapped_column("人員", Float(53))

class SalesBacklog(Base):
    __tablename__ = "T_OrderSalesBacklog"
    __table_args__ = {"extend_existing": True}

    年月: Mapped[int] = mapped_column("年月", Integer, primary_key=True)
    セグメント: Mapped[str] = mapped_column("セグメント", VARCHAR(10), primary_key=True)
    科目: Mapped[str] = mapped_column("科目", VARCHAR(10), primary_key=True)
    金額: Mapped[float] = mapped_column("金額", Float(53))

class ConstructionSuspenseAccounts(Base):
    __tablename__ = "T_ConstructionAccrual"
    __table_args__ = {"extend_existing": True}

    年月: Mapped[int] = mapped_column("年月", Integer, primary_key=True)
    セグメント: Mapped[str] = mapped_column("セグメント", VARCHAR(10), primary_key=True)
    金額: Mapped[float] = mapped_column("金額", Float(53))

class ItemizedInventoryDetails(Base):
    __tablename__ = "T_ItemInventoryDetails"
    __table_args__ = {"extend_existing": True}

    年月: Mapped[int] = mapped_column("年月", Integer, primary_key=True)
    セグメント: Mapped[str] = mapped_column("セグメント", VARCHAR(10), primary_key=True)
    科目: Mapped[str] = mapped_column("科目", VARCHAR(20), primary_key=True)
    科目コード: Mapped[str] = mapped_column("科目コード", VARCHAR(10), primary_key=True)
    金額区分: Mapped[str] = mapped_column("金額区分", VARCHAR(20), primary_key=True)
    金額: Mapped[float] = mapped_column("金額", Float(53))

class DirectExpenses(Base):
    __tablename__ = "T_DirectExpenses"
    __table_args__ = {"extend_existing": True}

    年月: Mapped[int] = mapped_column("年月", Integer, primary_key=True)
    SBU: Mapped[str] = mapped_column("SBU", VARCHAR(10), primary_key=True)
    金額: Mapped[float] = mapped_column("金額", Float(53))

class PurchasePriceGap(Base):
    __tablename__ = "T_PurchasePriceGap"
    __table_args__ = {"extend_existing": True}

    column1: Mapped[str] = mapped_column("年月", VARCHAR(50), primary_key=True)
    column2: Mapped[str] = mapped_column("元帳", VARCHAR(50))
    column3: Mapped[str] = mapped_column("事業領域", VARCHAR(50))
    column4: Mapped[str] = mapped_column("プラント", VARCHAR(50))
    column5: Mapped[str] = mapped_column("利益センタ", VARCHAR(50))
    column6: Mapped[str] = mapped_column("勘定コード", VARCHAR(50))
    column7: Mapped[str] = mapped_column("勘定コードテキスト", VARCHAR(50))
    column8: Mapped[str] = mapped_column("伝票番号", VARCHAR(50), primary_key=True)
    column9: Mapped[str] = mapped_column("明細", VARCHAR(50), primary_key=True)
    column10: Mapped[str] = mapped_column("伝票タイプ", VARCHAR(50))
    column11: Mapped[str] = mapped_column("借方伝票金額", VARCHAR(50))
    column12: Mapped[str] = mapped_column("貸方伝票金額", VARCHAR(50))
    column13: Mapped[str] = mapped_column("取引通貨", VARCHAR(50))
    column14: Mapped[str] = mapped_column("借方国内金額", VARCHAR(50))
    column15: Mapped[str] = mapped_column("貸方国内金額", VARCHAR(50))
    column16: Mapped[str] = mapped_column("会社コード通貨", VARCHAR(50))
    column17: Mapped[str] = mapped_column("会計年度", VARCHAR(50))
    column18: Mapped[str] = mapped_column("転記日付", VARCHAR(50))
    column19: Mapped[str] = mapped_column("伝票日付", VARCHAR(50))
    column20: Mapped[str] = mapped_column("登録日付", VARCHAR(50))
    column21: Mapped[str] = mapped_column("ユーザ名", VARCHAR(50))
    column22: Mapped[str] = mapped_column("原価センタ", VARCHAR(50))
    column23: Mapped[str] = mapped_column("指図", VARCHAR(50))
    column24: Mapped[str] = mapped_column("WBS 要素", VARCHAR(50))
    column25: Mapped[str] = mapped_column("参照伝票", VARCHAR(50))
    column26: Mapped[str] = mapped_column("明細テキスト", VARCHAR(50))
    column27: Mapped[str] = mapped_column("ソートキー", VARCHAR(50))
    column28: Mapped[str] = mapped_column("品目", VARCHAR(50))
    column29: Mapped[str] = mapped_column("品目テキスト", VARCHAR(50))
    column30: Mapped[str] = mapped_column("評価クラス", VARCHAR(50))
    column31: Mapped[str] = mapped_column("品目タイプ", VARCHAR(50))
    column32: Mapped[str] = mapped_column("受注", VARCHAR(50))
    column33: Mapped[str] = mapped_column("SO 明細", VARCHAR(50))
    column34: Mapped[str] = mapped_column("請求伝票", VARCHAR(50))
    column35: Mapped[str] = mapped_column("代替参照番号", VARCHAR(50))
    column36: Mapped[str] = mapped_column("購買伝票", VARCHAR(50))
    column37: Mapped[str] = mapped_column("明細_2", VARCHAR(50))

class ItemList(Base):
    __tablename__ = "T_ItemList"
    __table_args__ = {"extend_existing": True}

    column1: Mapped[str] = mapped_column("年月", VARCHAR(50), primary_key=True)
    column2: Mapped[str] = mapped_column("品目コード", VARCHAR(50), primary_key=True)
    column3: Mapped[str] = mapped_column("ﾌﾟﾗﾝﾄ", VARCHAR(50))
    column4: Mapped[str] = mapped_column("品目テキスト", VARCHAR(50))
    column5: Mapped[str] = mapped_column("品目Ty", VARCHAR(50))
    column6: Mapped[str] = mapped_column("削F", VARCHAR(50))
    column7: Mapped[str] = mapped_column("品目ｸﾞﾙｰﾌﾟ", VARCHAR(50))
    column8: Mapped[str] = mapped_column("旧品目ｺｰﾄﾞ", VARCHAR(50))
    column9: Mapped[str] = mapped_column("数単", VARCHAR(50))
    column10: Mapped[str] = mapped_column("文書番号", VARCHAR(50))
    column11: Mapped[str] = mapped_column("図訂", VARCHAR(50))
    column12: Mapped[str] = mapped_column("サイズ/寸法", VARCHAR(50))
    column13: Mapped[str] = mapped_column("主構成物質", VARCHAR(50))
    column14: Mapped[str] = mapped_column("PL品目ST", VARCHAR(50))
    column15: Mapped[str] = mapped_column("PL有効開始", VARCHAR(50))
    column16: Mapped[str] = mapped_column("販売ST", VARCHAR(50))
    column17: Mapped[str] = mapped_column("販有効開始", VARCHAR(50))
    column18: Mapped[str] = mapped_column("購買Gr", VARCHAR(50))
    column19: Mapped[str] = mapped_column("MRPﾀｲﾌﾟ", VARCHAR(50))
    column20: Mapped[str] = mapped_column("MRP管理者", VARCHAR(50))
    column21: Mapped[str] = mapped_column("調Ty", VARCHAR(50))
    column22: Mapped[str] = mapped_column("特調", VARCHAR(50))
    column23: Mapped[str] = mapped_column("内製", VARCHAR(50))
    column24: Mapped[str] = mapped_column("納入日数", VARCHAR(50))
    column25: Mapped[str] = mapped_column("TLT", VARCHAR(50))
    column26: Mapped[str] = mapped_column("入庫日数", VARCHAR(50))
    column27: Mapped[str] = mapped_column("発注点", VARCHAR(50))
    column28: Mapped[str] = mapped_column("安全在庫", VARCHAR(50))
    column29: Mapped[str] = mapped_column("最小LTサイズ", VARCHAR(50))
    column30: Mapped[str] = mapped_column("最大LTサイズ", VARCHAR(50))
    column31: Mapped[str] = mapped_column("丸め数量", VARCHAR(50))
    column32: Mapped[str] = mapped_column("余裕キー", VARCHAR(50))
    column33: Mapped[str] = mapped_column("Bkfl", VARCHAR(50))
    column34: Mapped[str] = mapped_column("製計担当", VARCHAR(50))
    column35: Mapped[str] = mapped_column("保管場所", VARCHAR(50))
    column36: Mapped[str] = mapped_column("方針Gr", VARCHAR(50))
    column37: Mapped[str] = mapped_column("バルク", VARCHAR(50))
    column38: Mapped[str] = mapped_column("評価クラス", VARCHAR(50))
    column39: Mapped[str] = mapped_column("標準原価", VARCHAR(50))
    column40: Mapped[str] = mapped_column("原価LTサイズ", VARCHAR(50))
    column41: Mapped[str] = mapped_column("利可在庫", VARCHAR(50))
    column42: Mapped[str] = mapped_column("棚番", VARCHAR(50))
    column43: Mapped[str] = mapped_column("保管期限", VARCHAR(50))
    column44: Mapped[str] = mapped_column("品目階層", VARCHAR(50))
    column45: Mapped[str] = mapped_column("品目種別", VARCHAR(50))
    column46: Mapped[str] = mapped_column("Copy元ｺｰﾄﾞ", VARCHAR(50))
    column47: Mapped[str] = mapped_column("調分", VARCHAR(50))
    column48: Mapped[str] = mapped_column("調分Text", VARCHAR(50))
    column49: Mapped[str] = mapped_column("最終製造", VARCHAR(50))
    column50: Mapped[str] = mapped_column("最終入庫", VARCHAR(50))
    column51: Mapped[str] = mapped_column("最終出庫", VARCHAR(50))
    column52: Mapped[str] = mapped_column("表面処理", VARCHAR(50))
    column53: Mapped[str] = mapped_column("熱処理", VARCHAR(50))
    column54: Mapped[str] = mapped_column("展開STOP", VARCHAR(50))
    column55: Mapped[str] = mapped_column("工品F", VARCHAR(50))
    column56: Mapped[str] = mapped_column("LT積上げ", VARCHAR(50))
    column57: Mapped[str] = mapped_column("設計出図", VARCHAR(50))
    column58: Mapped[str] = mapped_column("旧Sys登録", VARCHAR(50))
    column59: Mapped[str] = mapped_column("棚卸ｻｲｸﾙ", VARCHAR(50))
    column60: Mapped[str] = mapped_column("設計登録者", VARCHAR(50))
    column61: Mapped[str] = mapped_column("設計登録", VARCHAR(50))
    column62: Mapped[str] = mapped_column("調分類登録", VARCHAR(50))
    column63: Mapped[str] = mapped_column("LT/LOT登録", VARCHAR(50))
    column64: Mapped[str] = mapped_column("購買登録日", VARCHAR(50))
    column65: Mapped[str] = mapped_column("品証登録日", VARCHAR(50))
    column66: Mapped[str] = mapped_column("製Ver登録", VARCHAR(50))
    column67: Mapped[str] = mapped_column("原積完了F", VARCHAR(50))
    column68: Mapped[str] = mapped_column("ST解除F", VARCHAR(50))
    column69: Mapped[str] = mapped_column("部品表登録", VARCHAR(50))
    column70: Mapped[str] = mapped_column("作手登録日", VARCHAR(50))
    column71: Mapped[str] = mapped_column("購情登録日", VARCHAR(50))
    column72: Mapped[str] = mapped_column("検規番号１", VARCHAR(50))
    column73: Mapped[str] = mapped_column("検規番号２", VARCHAR(50))
    column74: Mapped[str] = mapped_column("安在理由", VARCHAR(50))
    column75: Mapped[str] = mapped_column("安在見直し", VARCHAR(50))
    column76: Mapped[str] = mapped_column("記事欄１", VARCHAR(50))
    column77: Mapped[str] = mapped_column("記事欄２", VARCHAR(50))
    column78: Mapped[str] = mapped_column("生計対象品", VARCHAR(50))
    column79: Mapped[str] = mapped_column("支給区分", VARCHAR(50))
    column80: Mapped[str] = mapped_column("独所更新日", VARCHAR(50))
    column81: Mapped[str] = mapped_column("独所更時間", VARCHAR(50))
    column82: Mapped[str] = mapped_column("独立更新者", VARCHAR(50))
    column83: Mapped[str] = mapped_column("出荷止めF", VARCHAR(50))
    column84: Mapped[str] = mapped_column("備考", VARCHAR(50))
    column85: Mapped[str] = mapped_column("発注単位", VARCHAR(50))
    column86: Mapped[str] = mapped_column("ロットサイズ", VARCHAR(50))
    column87: Mapped[str] = mapped_column("総重量", VARCHAR(50))
    column88: Mapped[str] = mapped_column("まるめ理由", VARCHAR(50))
    column89: Mapped[str] = mapped_column("まるめ見直し期限", VARCHAR(50))
    column90: Mapped[str] = mapped_column("分類", VARCHAR(50))
    column91: Mapped[str] = mapped_column("保存期限", VARCHAR(50))
    column92: Mapped[str] = mapped_column("バッテリー", VARCHAR(50))
    column93: Mapped[str] = mapped_column("外部調達保管場所", VARCHAR(50))
    column94: Mapped[str] = mapped_column("棚番(N420)", VARCHAR(50))
    column95: Mapped[str] = mapped_column("棚番(NSNK)", VARCHAR(50))
    column96: Mapped[str] = mapped_column("棚番(NF00)", VARCHAR(50))
    column97: Mapped[str] = mapped_column("棚番(NF0S)", VARCHAR(50))
    column98: Mapped[str] = mapped_column("棚番(ND01)", VARCHAR(50))
    column99: Mapped[str] = mapped_column("クレーム集計区分", VARCHAR(50))
    column100: Mapped[str] = mapped_column("間接費グループ", VARCHAR(50))
    column101: Mapped[str] = mapped_column("トレース対象", VARCHAR(50))

class FinancialCostOfSales(Base):
    __tablename__ = "T_FinancialCostOfSales"
    __table_args__ = {"extend_existing": True}

    年月: Mapped[int] = mapped_column("年月", Integer, primary_key=True, autoincrement=False)
    金額: Mapped[float] = mapped_column("金額", Float(53))

class FinancialOperatingIncome(Base):
    __tablename__ = "T_FinancialOperatingIncome"
    __table_args__ = {"extend_existing": True}

    年月: Mapped[int] = mapped_column("年月", Integer, primary_key=True, autoincrement=False)
    金額: Mapped[float] = mapped_column("金額", Float(53))
